/**
 *
 *  OrderController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
using namespace drogon;
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r OrderController).
 * this class is a restful API controller.
 */
class OrderController: public drogon::HttpController<OrderController>
{
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    METHOD_ADD(OrderController::create,"/orders",Post);
    METHOD_ADD(OrderController::showOrders,"/orders",Get);
    //METHOD_ADD(OrderController::update,"",Put,Options);
    METHOD_LIST_END

    void create(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback);
    void showOrders(const HttpRequestPtr &req,
                    std::function<void(const HttpResponsePtr &)> &&callback);
//    void update(const HttpRequestPtr &req,
//                std::function<void(const HttpResponsePtr &)> &&callback);

};
